#Example 1

version: '3.8'

networks:
  test_moodle_network:
    driver: bridge

services:
  db_moodle:
    image: mariadb:10.6
    container_name: db_moodle
    environment:
      MYSQL_ROOT_PASSWORD: moodle
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    networks:
      - test_moodle_network
    volumes:
      - db_data:/var/lib/mysql

  instance_moodle:
    image: bitnami/moodle:4.5.3
    container_name: instance_moodle
    environment:
      - MOODLE_DATABASE_HOST=db_moodle
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_PASSWORD=moodle
    ports:
      - "8080:8080"
    networks:
      - test_moodle_network
    volumes:
      - moodledata:/bitnami/moodle
    depends_on:
      - db_moodle


  php_moodle:
    image: phpmyadmin/phpmyadmin
    container_name: php_moodle
    environment:
      PMA_HOST: db_moodle
      MYSQL_ROOT_PASSWORD: moodle
    ports:
      - "8081:80"
    networks:
      - test_moodle_network
    depends_on:
      - db_moodle

volumes:
  db_data:
  moodledata:


#Example 2
version: "3.8"

services:
  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - database

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_root_password

volumes:
  db_data:
  nginx_logs:

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
